In [1]:
# https://mp.weixin.qq.com/s/nIVle0slvWBMCW4Ui8oSzw
from lazypredict.Supervised import LazyClassifier
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split

In [2]:
data = load_iris()
X,y = data.data, data.target

In [3]:
print(type(X))
print(type(y))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [4]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [5]:
X.shape, y.shape

((150, 4), (150,))

In [6]:
X[:4,]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2]])

In [7]:
import collections
collections.Counter(y)

Counter({0: 50, 1: 50, 2: 50})

In [8]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [9]:
y_test

array([2, 1, 0, 2, 0, 2, 0, 1, 1, 1, 2, 1, 1, 1, 1, 0, 1, 1, 0, 0, 2, 1,
       0, 0, 2, 0, 0, 1, 1, 0])

In [12]:
clf = LazyClassifier(verbose=0, ignore_warnings=True, custom_metric=None)

这段代码的参数解释如下：

- `LazyClassifier`：用于初始化的分类器名称。
- `verbose`：控制分类器输出信息的程度。取值为0（禁用输出）或1（仅输出错误信息）。
- `ignore_warnings`：控制分类器忽略警告信息。取值为True（忽略）或False（不忽略）。
- `custom_metric`：用于自定义评估指标。可以设置为自定义函数，但在此例中未显示使用。
- `random_state`：用于初始化随机数生成器的状态。取值为0（随机）或1（严格有序）或其他整数。
- `shuffle`：控制数据是否被随机打乱。取值为True（随机打乱）或False（不随机打乱）。
- `n_jobs`：控制分类器并行处理的任务数量。取值为整数，表示并行处理的任务数量。
- `use_gpu`：控制分类器是否使用GPU。取值为True（使用GPU）或False（不使用GPU）。

这段代码主要用于创建`LazyClassifier`实例，以便在后续代码中使用该实例进行文本分类。


In [15]:
clf.classifiers

'all'

In [16]:
models,predictions = clf.fit(X_train, X_test, y_train, y_test)

 97%|█████████▋| 28/29 [00:57<00:03,  3.62s/it]

[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.044187 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 90
[LightGBM] [Info] Number of data points in the train set: 120, number of used features: 4
[LightGBM] [Info] Start training from score -1.123930
[LightGBM] [Info] Start training from score -1.176574
[LightGBM] [Info] Start training from score -1.003302
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No furth

100%|██████████| 29/29 [01:02<00:00,  2.17s/it]

[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No f

In [17]:
print(models)

                               Accuracy  Balanced Accuracy ROC AUC  F1 Score  \
Model                                                                          
BaggingClassifier                  1.00               1.00    None      1.00   
ExtraTreesClassifier               1.00               1.00    None      1.00   
DecisionTreeClassifier             1.00               1.00    None      1.00   
KNeighborsClassifier               1.00               1.00    None      1.00   
RandomForestClassifier             1.00               1.00    None      1.00   
SVC                                1.00               1.00    None      1.00   
SGDClassifier                      1.00               1.00    None      1.00   
NuSVC                              1.00               1.00    None      1.00   
Perceptron                         1.00               1.00    None      1.00   
LogisticRegression                 1.00               1.00    None      1.00   
LinearDiscriminantAnalysis         1.00 

In [20]:
type(models)

pandas.core.frame.DataFrame

In [21]:
models.shape

(27, 5)

在您提供的输出结果中，列出了多个分类模型在鸢尾花数据集上的性能表现。以下是对这些模型的简要介绍：

1. **BaggingClassifier**: 这是一个基于自举汇聚法（Bootstrap Aggregating）的集成模型，通过构建多个基分类器并对它们的预测结果进行投票来提高整体模型的性能。

2. **ExtraTreesClassifier**: 与随机森林类似，它是一个基于随机特征选择的集成方法，但是它在选择分裂节点时使用了全部特征，而不是最优特征，从而增加了模型的多样性。

3. **DecisionTreeClassifier**: 这是一个基于树结构的分类模型，通过递归地将数据集分割成越来越小的子集来进行决策。

4. **KNeighborsClassifier**: 这是一个基于实例的分类器，它根据最近邻居的类别来预测新实例的类别。

5. **RandomForestClassifier**: 这是一个集成方法，它构建多个决策树并将它们的预测结果进行投票，以提高模型的准确性和鲁棒性。

6. **SVC (Support Vector Classifier)**: 支持向量机是一种强大的分类器，它通过在高维空间中寻找最佳边界来区分不同的类别。

7. **SGDClassifier (Stochastic Gradient Descent Classifier)**: 这是一个基于随机梯度下降的线性分类器，适用于大规模数据集。

8. **NuSVC**: 这是SVC的一个变体，它允许一些分类错误，从而在保持高准确度的同时减少模型的复杂度。

9. **Perceptron**: 感知机是一种简单的线性二分类模型，通过迭代调整权重来最大化预测的准确度。

10. **LogisticRegression**: 逻辑回归是一种广泛使用的线性分类算法，它通过最大化数据的似然函数来估计概率。

11. **LinearDiscriminantAnalysis**: 线性判别分析是一种经典的线性分类方法，它通过找到最佳的线性组合特征来区分不同的类别。

12. **XGBClassifier**: 这是XGBoost算法的一个实现，它是一种基于梯度提升的集成学习算法，以其高效和准确度高而闻名。

13. **LGBMClassifier**: 这是LightGBM算法的一个实现，它是一种基于梯度提升的决策树算法，特点是快速且内存使用效率高。

14. **QuadraticDiscriminantAnalysis**: 二次判别分析是一种基于多元正态分布假设的分类方法，它通过二次方程来描述类别之间的边界。

15. **LabelSpreading**: 这是一种基于图的半监督学习方法，它通过传播标签信息来提高分类性能。

16. **ExtraTreeClassifier**: 这是另一个基于树的分类器，它的分裂规则与决策树不同，更注重随机性。

17. **GaussianNB**: 高斯朴素贝叶斯是一种基于贝叶斯定理的分类器，它假设特征之间相互独立。

18. **AdaBoostClassifier**: 自适应提升算法是一种集成方法，它通过迭代地调整每个样本的权重来提高模型的性能。

19. **LabelPropagation**: 这是一种基于图的半监督学习方法，它通过传播已知标签来预测未知标签。

20. **LinearSVC**: 这是SVC的一个变体，它使用线性核函数。

21. **RidgeClassifierCV**, **CalibratedClassifierCV**, **RidgeClassifier**: 这些都是基于岭回归的分类器，它们通过引入正则化项来防止过拟合。

22. **PassiveAggressiveClassifier**: 这是一种迭代的线性分类器，它通过逐步调整模型来最小化累积错误。

23. **NearestCentroid**: 这是一种基于最近质心的分类方法，它根据最近的均值向量（centroid）来预测类别。

24. **BernoulliNB**: 伯努利朴素贝叶斯是一种基于伯努利分布的朴素贝叶斯分类器，适用于二元特征。

25. **DummyClassifier**: 这是一个简单的基线模型，它的预测结果完全随机或者根据输入数据的某些统计特性来确定。

从您提供的输出结果来看，大多数模型在鸢尾花数据集上都达到了很高的准确度（1.00），这表明这些模型在该数据集上的性能非常出色。然而，也存在一些模型，如RidgeClassifierCV、CalibratedClassifierCV、RidgeClassifier、PassiveAggressiveClassifier、NearestCentroid、BernoulliNB和DummyClassifier，它们的准确度较低，这可能是由于模型本身的限制或者不适用于该数据集的特性。此外，我们还可以看到，不同的模型在训练时间上也有所不同，这在选择模型时也是一个需要考虑的因素。